matrix:
  include:
    - language: java
      jdk: oraclejdk8
      install: true
      script: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true
      cache:
        directories:
        - $HOME/.m2

    - sudo: required
      dist: trusty
      language: node_js
      node_js:
        - '7.0.0'

      addons:
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
          - google-chrome-beta

      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - google-chrome --version
        - cd src/main/web

      install:
        - npm install

      script:
        - npm run ng test -- --single-run=true --browsers Chrome
        - npm run build
