matrix:
  include:
    - language: java
      jdk: oraclejdk8
      install: true
      script: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true
      cache:
        directories:
        - $HOME/.m2

    - sudo: required
      dist: trusty
      language: node_js
      node_js:
        - '10.16.0'

      addons:
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
          - google-chrome-beta

      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - google-chrome --version
        - cd src/main/web/src/app
        - openssl aes-256-cbc -K $encrypted_8d0e4651946f_key -iv $encrypted_8d0e4651946f_iv -in app.config.ts.enc -out app.config.ts -d
        - cd ../../
      install:
        - npm install

      script:
        - npm run test-once
        - travis_wait npm run build
