# todo java 11
FROM arm32v7/tomee:8-jre-7.1.0-plus

RUN rm -rf /usr/local/tomee/webapps/ROOT/
RUN rm -f /usr/local/tomee/webapps/ROOT.war
ADD target/memo-2.0.0.war /usr/local/tomee/webapps/ROOT.war
ADD tomee.xml /usr/local/tomee/conf/
ADD server.xml /usr/local/tomee/conf/
ADD tomcat-users.xml /usr/local/tomee/conf/
ADD settings.xml /usr/local/tomee/conf/

ADD setenv-arm32v7.sh /usr/local/tomee/bin/setenv.sh

ENV EMAIL_HOST {EMAIL_HOST}
ENV EMAIL_USER {EMAIL_HOST}
ENV EMAIL_USER_NAME {EMAIL_HOST}
ENV EMAIL_PASSWORD {EMAIL_HOST}
ENV EMAIL_PORT {EMAIL_HOST}

ENV ADMIN_EMAIL {EMAIL_HOST}
ENV ADMIN_PASSWORD {EMAIL_HOST}

ENV JWT_ACCESS_TOKEN_KEY {EMAIL_HOST}
ENV JWT_REFRESH_TOKEN_KEY {EMAIL_HOST}

ENV SENTRY_DSN {SENTRY_DSN}
ENV SENTRY_RELEASE {SENTRY_RELEASE}

CMD ["catalina.sh", "run"]

HEALTHCHECK --interval=10s --timeout=3s --retries=6 CMD curl -f http://localhost:8080/ROOT.com/health || exit 1
