version: "3.7"
services:
  memo:
    container_name: memoshop
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    restart: always
    image: meilenwoelfe/shop:latest
    volumes:
      - /usr/share/tomcat8/MemoShop/pictures:/usr/share/tomcat8/MemoShop/pictures
    ports:
      - 8080:8080
    logging:
      options:
        max-size: "50m"

