version: "3.7"
services:
  memo:
    container_name: memoshop
    build:
      context: .
      dockerfile: Dockerfile-arm32v7
      network: host
    restart: always
    image: meilenwoelfe/shop:1.0.0-arm32v7
    volumes:
      - /Memoshop/pictures:/root/MemoShop/pictures
    ports:
      - 8080:8080
    logging:
      options:
        max-size: "50m"

