version: "3.7"
services:
  memo:
    container_name: memoshop
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    restart: always
    network_mode: host
    image: meilenshop/shop:1.0.0
    volumes:
      - /Memoshop/pictures:/root/MemoShop/pictures
    ports:
      - 8080:8080
    logging:
      options:
        max-size: "50m"

